server:
  port: 8888
  max-http-header-size: 2097152
  undertow:
    threads:
      worker: 128
spring:
  application:
    name: silence
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lemon?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driverClassName: com.mysql.cj.jdbc.Driver
---
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
mybatis-plus:
  type-aliases-package: com.lemon.silence.mybatis.entity
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_null
      column-like: true
    # sql解析缓存，开启后多租户@SqlParser生效
    sql-parser-cache: true
    # 刷新mapper用于调试
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 1级缓存关闭
    local-cache-scope: statement

restTemplate:
  readTimeout: 5000
  connectTimeout: 5000