server:
  port: 8080
  max-http-header-size: 2097152
spring:
  application:
    name: silence
---
spring:
  datasource:
    url: jdbc:mysql://192.168.179.193:9999/lemon?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:/mapper/**.xml
restTemplate:
  readTimeout: 5000
  connectTimeout: 5000